### ISSUE TITLE
Setter function from useSsrState not working as expected

### ISSUE THREAD

**Issue by JulianSoto** [AlexSergey/issr#4]
From React API docs:

> [When setting a state using hooks] if the new state is computed using the previous state, you can pass a function to setState. The function will receive the previous value, and return an updated value

That means, if we had a `count` state, for example, and we wanted to increase its value by 1, we would have to necessarily know the current state, so in this case the solution is to pass a function to `setCount`which gets the current value and return the next one:

`setCount(currentCount => currentCount + 1)`

This works totally fine when using the `useState` hook from React. Unfortunately `useSsrState` from iSSR does not work as expected. After the first render if we try to update the state, it only changes once. In this case, being 0 the initial value of `count` and after using `setCount(currentCount => currentCount + 1)` once, `count`'s value now becomes 1. This is expected, but then if we try to set count again, it doesn't work anymore, so the value stays in 1.

**Comment by AlexSergey** [comment]
Thank you for your attention to the project! I checked the code and make some example:
I created the component
```jsx
const App = () => {
  const [state, setState] = useSsrState(0);

  useSsrEffect(async () => {
    setState(state => state + 1);
  });

  return (
    <div>
      <h1>{state}</h1>
    </div>
  );
};
```

and everything works well.

In the issr's source I handle setState's callback:

```js
const s = typeof componentState === 'function' ? componentState(state) : componentState;
initState[key] = s;
```

Maybe I miss something, could you please provide my some example with this issue? Keep attention please to add necessary @issr/babel-plugin
