### ISSUE TITLE
TypeError: o is not a function

### ISSUE THREAD

**Issue by hyphen1370** [AlexSergey/issr#5]
Hello, 

I am trying to use useSsrState in react ssr that is setup in Azure function with Javascript. Since Azure funciton with Javascript doesn't support any module javascript like import issrPkg from '@issr/core'; I have to use .mjs for each file. 

After I create a page like these: 
import issrPkg from '@issr/core';
const { useSsrState, useSsrEffect } = issrPkg;
const BackupRestoreChecklistDate = (content) => {
    const [backupRestoreChecklistDateDisplay, setbackupRestoreChecklistDateDisplay] = useSsrState("test");
    return (
        createElement("div", {key: generateReactKeys()}, "dasfgdfgdfg")
    )
}
export default BackupRestoreChecklistDate;

it gave me the error of TypeError: Cannot read property 'length' of null,TypeError: o is not a function

The version is "@issr/core": "^1.1.0",

Is there any fix for this setup? 
Thanks

**Comment by hyphen1370** [comment]
Also, when I imported as import { useSsrState } from '@issr/core';

error: 

import { useSsrState } from '@issr/core';
         ^^^^^^^^^^^
SyntaxError: Named export 'useSsrState' not found. The requested module '@issr/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@issr/core';
const { useSsrState } = pkg;

**Comment by AlexSergey** [comment]
I'm not sure that "issr" supports mjs currently. I recommend pre-build your script by webpack to compile all modules and tendencies together and import it like one big JS file. This preparation can help you avoid this problem.
