### ISSUE TITLE
Documentation outdated and Usage Examples not Working

### ISSUE THREAD

**Issue by flobby** [AlexSergey/issr#7]
It looks like the update from 1.2.0 to 2.0.0 has a major change in usage. Before 2.0 the id was autogenerated. Now its required (although not by typescript definition but the it raises an error) and no further context given.

Is version 2.0.0 ready to be used or still work in progress?

**Comment by AlexSergey** [comment]
@flobby , Hello! Thank you for your comment. In version 2.0.0 issr still use babel-loader to append ID in the state hook. Could you provide me details, what is the issue?

**Comment by flobby** [comment]
Can't really say what/how buw the latest version worked for me. I guess it was a CRA setup issue.

Thanks!
